/**
 * Sample Profile Data for Demo Mode
 * Provides realistic profiling data for first-time users
 * @module panel/demo/sampleProfile
 */

import type { CommitData } from '@/shared/types';
import type { PerformanceMetrics } from '@/panel/stores/profilerStore';

/**
 * Generate sample commits showing various performance patterns
 */
export function generateSampleCommits(): CommitData[] {
  const commits: CommitData[] = [];
  const baseTime = Date.now();

  // Commit 1: Initial render
  commits.push({
    id: 'commit_1',
    timestamp: baseTime,
    nodes: [
      {
        id: 1,
        displayName: 'App',
        actualDuration: 25,
        baseDuration: 25,
        props: { theme: 'dark' },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: null,
        children: [2, 3, 4],
        isMemoized: false,
      },
      {
        id: 2,
        displayName: 'Header',
        actualDuration: 5,
        baseDuration: 5,
        props: { title: 'Dashboard' },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 1,
        children: [5, 6],
        isMemoized: false,
      },
      {
        id: 3,
        displayName: 'Sidebar',
        actualDuration: 8,
        baseDuration: 8,
        props: { collapsed: false },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 1,
        children: [7, 8, 9],
        isMemoized: false,
      },
      {
        id: 4,
        displayName: 'Main',
        actualDuration: 10,
        baseDuration: 10,
        props: {},
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 1,
        children: [10],
        isMemoized: false,
      },
      {
        id: 5,
        displayName: 'Logo',
        actualDuration: 2,
        baseDuration: 2,
        props: {},
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 2,
        children: [],
        isMemoized: false,
      },
      {
        id: 6,
        displayName: 'Nav',
        actualDuration: 2,
        baseDuration: 2,
        props: { items: ['Home', 'Profile', 'Settings'] },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 2,
        children: [],
        isMemoized: false,
      },
      {
        id: 7,
        displayName: 'MenuItem',
        actualDuration: 2,
        baseDuration: 2,
        props: { label: 'Dashboard', icon: 'home' },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 3,
        children: [],
        isMemoized: true,
        memoType: 'React.memo',
      },
      {
        id: 8,
        displayName: 'MenuItem',
        actualDuration: 2,
        baseDuration: 2,
        props: { label: 'Analytics', icon: 'chart' },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 3,
        children: [],
        isMemoized: true,
        memoType: 'React.memo',
      },
      {
        id: 9,
        displayName: 'MenuItem',
        actualDuration: 2,
        baseDuration: 2,
        props: { label: 'Settings', icon: 'settings' },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 3,
        children: [],
        isMemoized: true,
        memoType: 'React.memo',
      },
      {
        id: 10,
        displayName: 'DataGrid',
        actualDuration: 8,
        baseDuration: 8,
        props: { columns: ['Name', 'Status', 'Date'] },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 4,
        children: [11, 12, 13, 14],
        isMemoized: false,
      },
      {
        id: 11,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 0 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 10,
        children: [],
        isMemoized: false,
      },
      {
        id: 12,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 1 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 10,
        children: [],
        isMemoized: false,
      },
      {
        id: 13,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 2 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 10,
        children: [],
        isMemoized: false,
      },
      {
        id: 14,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 3 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 10,
        children: [],
        isMemoized: false,
      },
    ],
    rootId: 1,
    priorityLevel: 'Normal',
    duration: 25,
    interactions: [],
  });

  // Commit 2: Update with wasted renders
  commits.push({
    id: 'commit_2',
    timestamp: baseTime + 5000,
    nodes: [
      {
        id: 15,
        displayName: 'App',
        actualDuration: 30,
        baseDuration: 30,
        props: { theme: 'dark', counter: 1 },
        prevProps: { theme: 'dark' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: null,
        children: [16, 17, 18],
        isMemoized: false,
      },
      {
        id: 16,
        displayName: 'Header',
        actualDuration: 5,
        baseDuration: 5,
        props: { title: 'Dashboard' },
        prevProps: { title: 'Dashboard' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 15,
        children: [19, 20],
        isMemoized: false,
      },
      {
        id: 17,
        displayName: 'Sidebar',
        actualDuration: 10,
        baseDuration: 10,
        props: { collapsed: false },
        prevProps: { collapsed: false },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 15,
        children: [21, 22, 23],
        isMemoized: false,
      },
      {
        id: 18,
        displayName: 'Main',
        actualDuration: 12,
        baseDuration: 12,
        props: { counter: 1 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 15,
        children: [24],
        isMemoized: false,
      },
      {
        id: 19,
        displayName: 'Logo',
        actualDuration: 3,
        baseDuration: 3,
        props: {},
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 16,
        children: [],
        isMemoized: false,
      },
      {
        id: 20,
        displayName: 'Nav',
        actualDuration: 2,
        baseDuration: 2,
        props: { items: ['Home', 'Profile', 'Settings'] },
        prevProps: { items: ['Home', 'Profile', 'Settings'] },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 16,
        children: [],
        isMemoized: false,
      },
      {
        id: 21,
        displayName: 'MenuItem',
        actualDuration: 3,
        baseDuration: 3,
        props: { label: 'Dashboard', icon: 'home' },
        prevProps: { label: 'Dashboard', icon: 'home' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 17,
        children: [],
        isMemoized: true,
        memoType: 'React.memo',
      },
      {
        id: 22,
        displayName: 'MenuItem',
        actualDuration: 3,
        baseDuration: 3,
        props: { label: 'Analytics', icon: 'chart' },
        prevProps: { label: 'Analytics', icon: 'chart' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 17,
        children: [],
        isMemoized: true,
        memoType: 'React.memo',
      },
      {
        id: 23,
        displayName: 'MenuItem',
        actualDuration: 3,
        baseDuration: 3,
        props: { label: 'Settings', icon: 'settings' },
        prevProps: { label: 'Settings', icon: 'settings' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 17,
        children: [],
        isMemoized: true,
        memoType: 'React.memo',
      },
      {
        id: 24,
        displayName: 'DataGrid',
        actualDuration: 10,
        baseDuration: 10,
        props: { columns: ['Name', 'Status', 'Date'], counter: 1 },
        prevProps: { columns: ['Name', 'Status', 'Date'] },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 18,
        children: [25, 26, 27, 28],
        isMemoized: false,
      },
      {
        id: 25,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 0 },
        prevProps: { index: 0 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 24,
        children: [],
        isMemoized: false,
      },
      {
        id: 26,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 1 },
        prevProps: { index: 1 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 24,
        children: [],
        isMemoized: false,
      },
      {
        id: 27,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 2 },
        prevProps: { index: 2 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 24,
        children: [],
        isMemoized: false,
      },
      {
        id: 28,
        displayName: 'Row',
        actualDuration: 2,
        baseDuration: 2,
        props: { index: 3 },
        prevProps: { index: 3 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 24,
        children: [],
        isMemoized: false,
      },
    ],
    rootId: 15,
    priorityLevel: 'Normal',
    duration: 30,
    interactions: [{ id: 1, name: 'state-change', timestamp: baseTime + 5000 }],
  });

  // Commit 3: Optimized render (fewer wasted renders with React.memo)
  commits.push({
    id: 'commit_3',
    timestamp: baseTime + 10000,
    nodes: [
      {
        id: 29,
        displayName: 'App',
        actualDuration: 15,
        baseDuration: 15,
        props: { theme: 'light', counter: 2 },
        prevProps: { theme: 'dark', counter: 1 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: null,
        children: [30, 31, 32],
        isMemoized: false,
      },
      {
        id: 30,
        displayName: 'Header',
        actualDuration: 5,
        baseDuration: 5,
        props: { title: 'Dashboard' },
        prevProps: { title: 'Dashboard' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 29,
        children: [33],
        isMemoized: false,
      },
      {
        id: 31,
        displayName: 'Sidebar',
        actualDuration: 3,
        baseDuration: 3,
        props: { collapsed: true },
        prevProps: { collapsed: false },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 29,
        children: [],
        isMemoized: false,
      },
      {
        id: 32,
        displayName: 'Main',
        actualDuration: 6,
        baseDuration: 6,
        props: { counter: 2 },
        prevProps: { counter: 1 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 29,
        children: [34],
        isMemoized: false,
      },
      {
        id: 33,
        displayName: 'Nav',
        actualDuration: 4,
        baseDuration: 4,
        props: { items: ['Home', 'Profile', 'Settings'] },
        prevProps: { items: ['Home', 'Profile', 'Settings'] },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 30,
        children: [],
        isMemoized: false,
      },
      // Logo and MenuItems are memoized and didn't re-render - they don't appear in this commit
      {
        id: 34,
        displayName: 'DataGrid',
        actualDuration: 5,
        baseDuration: 5,
        props: { columns: ['Name', 'Status', 'Date'], counter: 2 },
        prevProps: { columns: ['Name', 'Status', 'Date'], counter: 1 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 32,
        children: [35, 36, 37, 38],
        isMemoized: false,
      },
      {
        id: 35,
        displayName: 'Row',
        actualDuration: 1,
        baseDuration: 1,
        props: { index: 0 },
        prevProps: { index: 0 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 34,
        children: [],
        isMemoized: false,
      },
      {
        id: 36,
        displayName: 'Row',
        actualDuration: 1,
        baseDuration: 1,
        props: { index: 1 },
        prevProps: { index: 1 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 34,
        children: [],
        isMemoized: false,
      },
      {
        id: 37,
        displayName: 'Row',
        actualDuration: 1,
        baseDuration: 1,
        props: { index: 2 },
        prevProps: { index: 2 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 34,
        children: [],
        isMemoized: false,
      },
      {
        id: 38,
        displayName: 'Row',
        actualDuration: 1,
        baseDuration: 1,
        props: { index: 3 },
        prevProps: { index: 3 },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 34,
        children: [],
        isMemoized: false,
      },
    ],
    rootId: 29,
    priorityLevel: 'Normal',
    duration: 15,
    interactions: [{ id: 2, name: 'state-change', timestamp: baseTime + 10000 }],
  });

  // Commit 4: Expensive computation
  commits.push({
    id: 'commit_4',
    timestamp: baseTime + 15000,
    nodes: [
      {
        id: 39,
        displayName: 'App',
        actualDuration: 120,
        baseDuration: 120,
        props: { theme: 'light' },
        prevProps: { theme: 'light' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: null,
        children: [40, 41],
        isMemoized: false,
      },
      {
        id: 40,
        displayName: 'Header',
        actualDuration: 5,
        baseDuration: 5,
        props: { title: 'Analytics' },
        prevProps: { title: 'Dashboard' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 39,
        children: [],
        isMemoized: false,
      },
      {
        id: 41,
        displayName: 'ExpensiveChart',
        actualDuration: 100,
        baseDuration: 100,
        props: { data: 'large-dataset' },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 39,
        children: [42, 43, 44, 45, 46],
        isMemoized: false,
      },
      {
        id: 42,
        displayName: 'ChartBar',
        actualDuration: 20,
        baseDuration: 20,
        props: { index: 0, value: 100 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 41,
        children: [],
        isMemoized: false,
      },
      {
        id: 43,
        displayName: 'ChartBar',
        actualDuration: 20,
        baseDuration: 20,
        props: { index: 1, value: 80 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 41,
        children: [],
        isMemoized: false,
      },
      {
        id: 44,
        displayName: 'ChartBar',
        actualDuration: 20,
        baseDuration: 20,
        props: { index: 2, value: 60 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 41,
        children: [],
        isMemoized: false,
      },
      {
        id: 45,
        displayName: 'ChartBar',
        actualDuration: 20,
        baseDuration: 20,
        props: { index: 3, value: 40 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 41,
        children: [],
        isMemoized: false,
      },
      {
        id: 46,
        displayName: 'ChartBar',
        actualDuration: 20,
        baseDuration: 20,
        props: { index: 4, value: 20 },
        prevProps: {},
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 41,
        children: [],
        isMemoized: false,
      },
    ],
    rootId: 39,
    priorityLevel: 'Normal',
    duration: 120,
    interactions: [{ id: 3, name: 'state-change', timestamp: baseTime + 15000 }],
  });

  // Commit 5: Memo optimization working
  commits.push({
    id: 'commit_5',
    timestamp: baseTime + 20000,
    nodes: [
      {
        id: 47,
        displayName: 'App',
        actualDuration: 10,
        baseDuration: 10,
        props: { theme: 'light' },
        prevProps: { theme: 'light' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: null,
        children: [48, 49],
        isMemoized: false,
      },
      {
        id: 48,
        displayName: 'Header',
        actualDuration: 5,
        baseDuration: 5,
        props: { title: 'Analytics' },
        prevProps: { title: 'Analytics' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 47,
        children: [],
        isMemoized: false,
      },
      {
        id: 49,
        displayName: 'MemoizedChart',
        actualDuration: 3,
        baseDuration: 3,
        props: { data: 'large-dataset' },
        prevProps: { data: 'large-dataset' },
        state: {},
        prevState: {},
        hasContextChanged: false,
        parentId: 47,
        children: [],
        isMemoized: true,
        memoType: 'React.memo',
      },
    ],
    rootId: 47,
    priorityLevel: 'Normal',
    duration: 10,
    interactions: [{ id: 4, name: 'state-change', timestamp: baseTime + 20000 }],
  });

  return commits;
}

/**
 * Generate sample performance metrics
 */
export function generateSampleMetrics(): PerformanceMetrics {
  return {
    score: 75,
    averageRenderTime: 40,
    wastedRenderRate: 30,
    averageMemoHitRate: 58.3,
    totalComponents: 14,
  };
}

/**
 * Sample profile for demo mode
 */
export const sampleProfile = {
  version: 1,
  metadata: {
    title: 'Demo Profile',
    description: 'Sample profiling data demonstrating React performance optimization techniques',
    url: 'https://demo.react-perf-profiler.com',
    userAgent: 'Mozilla/5.0 (Demo)',
    screenResolution: '1920x1080',
    devicePixelRatio: 2,
  },
  commits: generateSampleCommits(),
  metrics: generateSampleMetrics(),
  exportDate: new Date().toISOString(),
};

export default sampleProfile;
